# Generated by Django 6.1 on 2026-09-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_verified_customuser_mfa_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Customer profile picture or photo', null=True, upload_to='avatars/'),
        ),
    ]
