# Generated by Django 6.1 on 2026-08-31 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('chauffeur', '0002_surcharge_zone_fixedroute_vehiclephoto_and_more'),
        ('payments', '0001_initial'),
        ('tours', '0002_tour_relatedtour_tourdate_tourfaq_tourhighlight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.coupon'),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingstatuslog',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='bookingstatuslog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chauffeurbooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chauffeur_booking', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='chauffeurbooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='chauffeur.vehicle'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_booking', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tours.tour'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='tour_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tours.tourdate'),
        ),
        migrations.AddField(
            model_name='tourbookingguest',
            name='tour_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='bookings.tourbooking'),
        ),
    ]
