# Generated by Django 6.1 on 2026-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Credit Card (Stripe)'), ('OFFLINE', 'Pay on Arrival / Cash to Chauffeur'), ('BANK_TRANSFER', 'Bank Wire Transfer (SEPA / IBAN)'), ('PAYPAL', 'PayPal')], default='STRIPE', max_length=30),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid / Pending Collection'), ('PAID', 'Paid & Reconciled'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20),
        ),
    ]
