# Generated by Django 6.1 on 2026-09-07 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_payment_method_booking_payment_status'),
        ('tours', '0013_migrate_tour_dates_and_seed_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='external_reference',
            field=models.CharField(blank=True, help_text='External OTA booking reference ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, help_text='If status is HELD, auto-expire and release capacity after this time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('DIRECT', 'Direct Website'), ('GETYOURGUIDE', 'GetYourGuide'), ('VIATOR', 'Viator'), ('MANUAL', 'Manual (Phone/Agent)'), ('HOTEL_AGENT', 'Hotel Agent'), ('OTHER_OTA', 'Other OTA')], default='DIRECT', max_length=20),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='tours.departure'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='departure_capacity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='tours.departurecapacity'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='tours.vehicletype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('HELD', 'Held / Reserved'), ('PENDING', 'Pending'), ('PENDING_PAYMENT', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='PENDING', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookingstatuslog',
            name='new_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='bookingstatuslog',
            name='old_status',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.tourdate'),
        ),
        migrations.CreateModel(
            name='GuaranteedReattempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('WEATHER', 'Weather Conditions / Aurora Not Visible'), ('OPERATIONAL', 'Operational Issue'), ('OTHER', 'Other')], default='WEATHER', max_length=20)),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible for Re-attempt'), ('REBOOKED', 'Rebooked to New Departure'), ('DECLINED', 'Customer Declined'), ('EXPIRED', 'Offer Expired')], default='ELIGIBLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('original_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reattempt_from', to='bookings.booking')),
                ('original_departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reattempts_originating', to='tours.departure')),
                ('reattempt_booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempt_to', to='bookings.booking')),
                ('reattempt_departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts_received', to='tours.departure')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guaranteed Re-attempt',
                'verbose_name_plural': 'Guaranteed Re-attempts',
                'ordering': ['-created_at'],
            },
        ),
    ]
