# Generated by Django 6.1 on 2026-09-19 06:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_external_reference_booking_hold_expires_at_and_more'),
        ('payments', '0002_couponusage'),
        ('tours', '0013_migrate_tour_dates_and_seed_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Northern Lights Standard Guarantee, Aurora Premium Guarantee', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('guarantee_type', models.CharField(choices=[('REATTEMPT_ONLY', 'Re-attempt Only (no refund)'), ('REFUND_ONLY', 'Refund Only (no re-attempt)'), ('REATTEMPT_THEN_REFUND', 'Re-attempt first, then Refund if re-attempts exhausted')], default='REATTEMPT_THEN_REFUND', help_text='Determines the guarantee workflow: re-attempt, refund, or both', max_length=30)),
                ('max_reattempts', models.PositiveIntegerField(default=1, help_text='Maximum number of re-attempt opportunities permitted under this policy')),
                ('reattempt_window_days', models.PositiveIntegerField(default=7, help_text='Number of days after the original tour within which a re-attempt must be scheduled')),
                ('refund_eligible', models.BooleanField(default=True, help_text='Whether this policy allows refund eligibility (after re-attempts exhausted, if applicable)')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Percentage of original booking amount eligible for refund (e.g. 100 for full, 50 for half)', max_digits=5)),
                ('refund_review_required', models.BooleanField(default=True, help_text='If True, admin must manually review and approve refund before processing')),
                ('description', models.TextField(blank=True, help_text='Customer-facing explanation of the guarantee (shown on tour detail page)')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Full terms and conditions for this guarantee policy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guarantee Policy',
                'verbose_name_plural': 'Guarantee Policies',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='guaranteedreattempt',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guaranteed Re-attempt (Legacy)', 'verbose_name_plural': 'Guaranteed Re-attempts (Legacy)'},
        ),
        migrations.CreateModel(
            name='GuaranteeOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guests_count', models.PositiveIntegerField(help_text='Number of guests covered by this guarantee')),
                ('aurora_result', models.CharField(choices=[('PENDING', 'Result Pending'), ('SUCCESSFUL', 'Successful'), ('UNSUCCESSFUL', 'Unsuccessful')], default='PENDING', help_text='The outcome of the tour experience (e.g. Aurora visible = Successful)', max_length=20)),
                ('result_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('result_notes', models.TextField(blank=True, help_text='Staff notes about the experience result')),
                ('unsuccessful_reason', models.CharField(blank=True, choices=[('WEATHER', 'Weather Conditions / Aurora Not Visible'), ('OPERATIONAL', 'Operational Issue'), ('SAFETY', 'Safety Conditions'), ('OTHER', 'Other Reason')], help_text='Reason why the experience was unsuccessful', max_length=20)),
                ('reattempt_count', models.PositiveIntegerField(default=0, help_text='How many re-attempts have been used so far')),
                ('refund_status', models.CharField(choices=[('NONE', 'Not Applicable'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('REFUNDED', 'Refunded'), ('DENIED', 'Denied')], default='NONE', max_length=20)),
                ('refund_eligible', models.BooleanField(default=False, help_text='Whether this outcome qualifies for refund under the policy')),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated refund amount based on policy percentage', max_digits=10, null=True)),
                ('refund_reason', models.TextField(blank=True, help_text='Reason for refund eligibility or denial')),
                ('status', models.CharField(choices=[('TOUR_COMPLETED', 'Tour Completed — Awaiting Result'), ('AURORA_SUCCESSFUL', 'Experience Successful — Closed'), ('AURORA_UNSUCCESSFUL', 'Experience Unsuccessful'), ('REATTEMPT_ELIGIBLE', 'Re-attempt Eligible'), ('REATTEMPT_SCHEDULED', 'Re-attempt Scheduled'), ('REATTEMPT_COMPLETED', 'Re-attempt Completed'), ('REFUND_REVIEW', 'Refund Eligibility Under Review'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_PROCESSING', 'Refund Processing'), ('REFUNDED', 'Refunded'), ('DECLINED', 'Customer Declined — Closed'), ('CLOSED', 'Closed')], default='TOUR_COMPLETED', max_length=25)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal admin notes about this guarantee case')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(help_text='Original booking this guarantee outcome is for', on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_outcomes', to='bookings.booking')),
                ('departure', models.ForeignKey(help_text='Original departure the customer attended', on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_outcomes', to='tours.departure')),
                ('reattempt_booking', models.ForeignKey(blank=True, help_text='New booking created for the re-attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_reattempt_bookings', to='bookings.booking')),
                ('reattempt_departure', models.ForeignKey(blank=True, help_text='Departure scheduled for re-attempt', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_reattempts_received', to='tours.departure')),
                ('refund', models.ForeignKey(blank=True, help_text='Link to the actual payment refund record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_outcomes', to='payments.refund')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_outcomes_resolved', to=settings.AUTH_USER_MODEL)),
                ('result_recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_results_recorded', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_outcomes', to='tours.tour')),
                ('policy', models.ForeignKey(help_text='The guarantee policy that was applied (snapshot at time of outcome creation)', on_delete=django.db.models.deletion.PROTECT, related_name='outcomes', to='bookings.guaranteepolicy')),
            ],
            options={
                'verbose_name': 'Guarantee Outcome',
                'verbose_name_plural': 'Guarantee Outcomes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('OUTCOME_CREATED', 'Guarantee Outcome Created'), ('RESULT_RECORDED', 'Aurora/Experience Result Recorded'), ('REATTEMPT_ELIGIBLE', 'Marked Re-attempt Eligible'), ('REATTEMPT_SCHEDULED', 'Re-attempt Scheduled'), ('REATTEMPT_COMPLETED', 'Re-attempt Completed'), ('REFUND_REVIEW_STARTED', 'Refund Eligibility Review Started'), ('REFUND_APPROVED', 'Refund Approved'), ('REFUND_DENIED', 'Refund Denied'), ('REFUND_PROCESSING', 'Refund Processing Initiated'), ('REFUND_COMPLETED', 'Refund Completed'), ('CUSTOMER_DECLINED', 'Customer Declined Re-attempt/Refund'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Admin Note Added'), ('CLOSED', 'Outcome Closed')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=25)),
                ('new_status', models.CharField(blank=True, max_length=25)),
                ('reason', models.TextField(blank=True, help_text='Reason for this action')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data: booking refs, departure IDs, refund amounts, etc.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_audit_actions', to=settings.AUTH_USER_MODEL)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='bookings.guaranteeoutcome')),
            ],
            options={
                'verbose_name': 'Guarantee Audit Log',
                'verbose_name_plural': 'Guarantee Audit Logs',
                'ordering': ['timestamp'],
            },
        ),
    ]
