# Generated by Django 6.1 on 2026-09-19 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_guarantee_system_overhaul'),
        ('tours', '0014_guarantee_system_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Guest Info',
                'verbose_name_plural': 'Guest Info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('bookings.tourbookingguest',),
        ),
        migrations.AlterField(
            model_name='guaranteedreattempt',
            name='guests_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guaranteedreattempt',
            name='original_departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reattempts_originating', to='tours.departure'),
        ),
    ]
