# Generated by Django 6.1 on 2026-09-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_update_guaranteed_reattempt_and_guestinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guaranteedreattempt',
            name='guests_count',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Defaults to booking guest count or 1 if left blank'),
        ),
    ]
