# Generated by Django 6.1 on 2026-09-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_make_reattempt_guests_count_blank'),
        ('tours', '0015_cancellationpolicy_guide_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_free_booking',
            field=models.BooleanField(default=False, help_text='If True, this is a free booking — no payment required, info collection only'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text='Selected pickup point for this booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to='tours.tourpickup'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='pickup_notes',
            field=models.TextField(blank=True, default='', help_text="Customer's pickup instructions or hotel name"),
        ),
        migrations.CreateModel(
            name='BookingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='bookings.booking')),
                ('extra_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_addons', to='tours.tourextraservice')),
            ],
            options={
                'verbose_name': 'Booking Add-on',
                'verbose_name_plural': 'Booking Add-ons',
            },
        ),
        migrations.CreateModel(
            name='ChildSeatRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_type', models.CharField(choices=[('INFANT', 'Infant Carrier (0-12 months)'), ('TODDLER', 'Toddler Seat (1-4 years)'), ('CHILD', 'Child Seat (4-7 years)'), ('BOOSTER', 'Booster Seat (7-12 years)')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('child_age', models.PositiveIntegerField(help_text="Child's age in years")),
                ('approx_weight_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Approximate weight in kg', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_seat_requests', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Child Seat Request',
                'verbose_name_plural': 'Child Seat Requests',
            },
        ),
        migrations.CreateModel(
            name='BookingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tours.bookingquestion')),
                ('tour_booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='bookings.tourbooking')),
            ],
            options={
                'verbose_name': 'Booking Answer',
                'verbose_name_plural': 'Booking Answers',
                'unique_together': {('tour_booking', 'question')},
            },
        ),
    ]
