# Generated by Django 6.1 on 2026-08-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surcharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surcharge_category', models.CharField(choices=[('NIGHT', 'Night'), ('WEEKEND', 'Weekend'), ('HOLIDAY', 'Holiday'), ('PEAK', 'Peak Hour'), ('CUSTOM', 'Custom')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_type', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PERCENT', 'Percentage')], max_length=10)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('applicable_days', models.JSONField(default=list, help_text='[5, 6] for Sat/Sun')),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('boundary_polygon', models.JSONField(help_text='GeoJSON coordinates')),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('surcharge_type', models.CharField(choices=[('FLAT', 'Flat Fee'), ('PERCENT', 'Percentage')], default='FLAT', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FixedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('origin_name', models.CharField(max_length=200)),
                ('origin_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('origin_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_name', models.CharField(max_length=200)),
                ('destination_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('destination_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estimated_duration_min', models.IntegerField()),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('is_return_available', models.BooleanField(default=False)),
                ('return_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_routes', to='chauffeur.vehicleclass')),
            ],
        ),
        migrations.CreateModel(
            name='VehiclePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='vehicles/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chauffeur.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Mon, 6=Sun')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='chauffeur.vehicleclass')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availability_rules', to='chauffeur.zone')),
            ],
        ),
    ]
