# Generated by Django 6.1 on 2026-09-04 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0002_surcharge_zone_fixedroute_vehiclephoto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclephoto',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Cab Photo', 'verbose_name_plural': 'Cab Photos'},
        ),
        migrations.AddField(
            model_name='vehiclephoto',
            name='vehicle_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chauffeur.vehicleclass'),
        ),
        migrations.AlterField(
            model_name='vehiclephoto',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='chauffeur.vehicle'),
        ),
        migrations.CreateModel(
            name='ChauffeurInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_included', models.BooleanField(default=True, help_text='True = Included in your price, False = Extra charge')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_class', models.ForeignKey(blank=True, help_text='Applies to a specific vehicle class. Leave blank to apply globally to all classes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='chauffeur.vehicleclass')),
            ],
            options={
                'verbose_name': 'Chauffeur Inclusion / Exclusion',
                'verbose_name_plural': 'Chauffeur Inclusions & Exclusions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChauffeurSafetyStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_class', models.ForeignKey(blank=True, help_text='Applies to a specific vehicle class. Leave blank to apply globally to all classes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_standards', to='chauffeur.vehicleclass')),
            ],
            options={
                'verbose_name': 'Safety & Luxury Standard',
                'verbose_name_plural': 'Safety & Luxury Standards',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChauffeurServiceStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Standard policy or service guarantee', max_length=300)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_class', models.ForeignKey(blank=True, help_text='Applies to a specific vehicle class. Leave blank to apply globally to all classes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_standards', to='chauffeur.vehicleclass')),
            ],
            options={
                'verbose_name': 'Chauffeur Service Standard',
                'verbose_name_plural': 'Chauffeur Service Standards',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
