# Generated by Django 6.1 on 2026-09-19 06:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0004_generalize_fixed_price_transfers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedroute',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('10.00'), help_text='Distance in km (defaults to 10.0 if not calculated)', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='dropoff_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), help_text='Optional latitude (defaults to 0.0 if not geocoded)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='dropoff_lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), help_text='Optional longitude (defaults to 0.0 if not geocoded)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='estimated_duration_min',
            field=models.IntegerField(blank=True, default=20, help_text='Duration in minutes (defaults to 20 if not calculated)', null=True),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), help_text='Optional latitude (defaults to 0.0 if not geocoded)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.000000'), help_text='Optional longitude (defaults to 0.0 if not geocoded)', max_digits=9, null=True),
        ),
    ]
