# Generated by Django 6.1 on 2026-09-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0005_make_fixedroute_coords_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text='Features list or JSON (e.g. Wi-Fi, Heated Seats)'),
        ),
    ]
