# Generated by Django 6.1 on 2026-09-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeur', '0006_alter_vehicle_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedroute',
            name='currency',
            field=models.CharField(blank=True, default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='luggage_capacity',
            field=models.PositiveIntegerField(blank=True, default=2, help_text='Max luggage pieces for this transfer route'),
        ),
        migrations.AlterField(
            model_name='fixedroute',
            name='passenger_capacity',
            field=models.PositiveIntegerField(blank=True, default=4, help_text='Max passengers for this transfer route'),
        ),
    ]
