# Generated by Django 6.1 on 2026-09-07 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tours', '0013_migrate_tour_dates_and_seed_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('adapter_class', models.CharField(blank=True, help_text='Python dotted path to adapter, e.g. channels.adapters.gyg.GetYourGuideAdapter', max_length=200)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=False)),
                ('sync_interval_minutes', models.PositiveIntegerField(default=15)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_status', models.CharField(default='NEVER_RUN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OTA Channel',
                'verbose_name_plural': 'OTA Channels',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('AVAILABILITY_PUSH', 'Availability Push'), ('BOOKING_IMPORT', 'Booking Import'), ('CANCELLATION_SYNC', 'Cancellation Sync'), ('WEBHOOK_RECEIVED', 'Webhook Received')], max_length=30)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying')], default='SUCCESS', max_length=20)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('requires_attention', models.BooleanField(default=False, help_text='True if this failure needs manual admin review or notification')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='channels.channel')),
                ('departure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs', to='tours.departure')),
            ],
            options={
                'verbose_name': 'Channel Sync Log',
                'verbose_name_plural': 'Channel Sync Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
