# Generated by Django 6.1 on 2026-08-31 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('short_summary', models.TextField(help_text='Card description, max 200 chars')),
                ('overview', models.TextField(help_text='Rich text - full description')),
                ('duration_text', models.CharField(max_length=100)),
                ('meeting_point', models.CharField(blank=True, max_length=250, null=True)),
                ('transportation_info', models.TextField(blank=True, null=True)),
                ('accommodation_info', models.TextField(blank=True, null=True)),
                ('meal_info', models.TextField(blank=True, null=True)),
                ('event_ticket_info', models.TextField(blank=True, null=True)),
                ('cancellation_terms', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tours', to='tours.destination')),
                ('duration_band', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tours', to='tours.durationband')),
                ('experience_types', models.ManyToManyField(related_name='tours', to='tours.experiencetype')),
                ('seasons', models.ManyToManyField(related_name='tours', to='tours.season')),
                ('travel_style', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='tours', to='tours.travelstyle')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0)),
                ('related_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_tours', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_capacity', models.IntegerField()),
                ('booked_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD_OUT', 'Sold Out'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_included', models.BooleanField(default=True, help_text='True=Included, False=Excluded')),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tours/media/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('is_hero', models.BooleanField(default=False, help_text='Only one per tour')),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('PICKUP', 'Pickup'), ('DROPOFF', 'Dropoff')], default='PICKUP', max_length=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('min_quantity', models.IntegerField(default=1)),
                ('max_quantity', models.IntegerField(blank=True, null=True)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing', to='tours.season')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='TourReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='tours.tour')),
            ],
        ),
    ]
