# Generated by Django 6.1 on 2026-09-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_tourcategory_toursurrounding_wishlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['sort_order', 'name'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='destination',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, default='Popular', help_text='Filter tab e.g. Popular, Northern Europe, Scandinavia', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Short card tagline', max_length=250),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.TextField(blank=True, help_text='Key highlights / attractions (e.g. Santa Claus Village, Arktikum)'),
        ),
    ]
