# Generated by Django 6.1 on 2026-09-03 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_alter_country_options_alter_destination_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='badge_text',
            field=models.CharField(blank=True, help_text="Marketing badge ribbon e.g. 'Best Seller', '15% Off', 'Top Rated'", max_length=50),
        ),
        migrations.AddField(
            model_name='touritinerary',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo for this itinerary day', null=True, upload_to='tours/itineraries/'),
        ),
        migrations.CreateModel(
            name='TourExtraService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_type', models.CharField(choices=[('PER_PERSON', 'Per Person'), ('PER_BOOKING', 'Per Booking (Flat)')], default='PER_PERSON', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='tours.tour')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
