# Generated by Django 6.1 on 2026-09-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_tour_badge_text_touritinerary_image_tourextraservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
