# Generated by Django 6.1 on 2026-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_alter_tour_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencetype',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='country',
            name='is_featured_in_nav',
            field=models.BooleanField(default=True, help_text='Show in Destination Mega Menu sidebar'),
        ),
        migrations.AddField(
            model_name='destination',
            name='is_featured_in_nav',
            field=models.BooleanField(default=True, help_text='Show in Destination Mega Menu circular grid'),
        ),
        migrations.AddField(
            model_name='experiencetype',
            name='image',
            field=models.ImageField(blank=True, help_text='Circular thumbnail for Tour Mega Menu', null=True, upload_to='experiences/'),
        ),
        migrations.AddField(
            model_name='experiencetype',
            name='is_featured_in_nav',
            field=models.BooleanField(default=True, help_text='Show in Tour Mega Menu circular grid'),
        ),
    ]
