# Generated by Django 6.1 on 2026-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_experiencetype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_icon',
            field=models.ImageField(blank=True, help_text='Upload flag or icon for mega menu sidebar', null=True, upload_to='countries/flags/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='nav_icon',
            field=models.ImageField(blank=True, help_text='Upload circular icon/image for navigation mega menu', null=True, upload_to='destinations/nav_icons/'),
        ),
        migrations.AddField(
            model_name='experiencetype',
            name='nav_icon',
            field=models.ImageField(blank=True, help_text='Upload circular icon image for Tour Mega Menu', null=True, upload_to='experiences/nav_icons/'),
        ),
        migrations.AlterField(
            model_name='experiencetype',
            name='icon',
            field=models.CharField(blank=True, help_text='CSS icon class', max_length=100),
        ),
    ]
