# Generated by Django 6.1 on 2026-09-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_country_flag_icon_destination_nav_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_family_tour',
            field=models.BooleanField(default=False, help_text="Show in 'Family tours' category on homepage", verbose_name='Family Tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_group_tour',
            field=models.BooleanField(default=True, help_text="Show in 'Group tours' category on homepage", verbose_name='Group Tour'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_private_tour',
            field=models.BooleanField(default=False, help_text="Show in 'Private tours' category on homepage", verbose_name='Private Tour'),
        ),
    ]
