# Generated by Django 6.1 on 2026-09-07 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_tour_is_family_tour_tour_is_group_tour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text='Emoji or CSS icon class, e.g. 🚗', max_length=50)),
                ('default_capacity', models.PositiveIntegerField(help_text='Default seat count for this vehicle type')),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Vehicle Type',
                'verbose_name_plural': 'Vehicle Types',
                'ordering': ['sort_order', 'default_capacity'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='has_guaranteed_reattempt',
            field=models.BooleanField(default=False, help_text='Enable guaranteed re-attempt policy (e.g., Northern Lights). Failed experiences allow customers to re-attempt on the next available day.'),
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('SOLD_OUT', 'Sold Out'), ('BLOCKED', 'Blocked'), ('OPERATIONALLY_RESERVED', 'Operationally Reserved')], default='OPEN', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Departure',
                'verbose_name_plural': 'Departures',
                'ordering': ['date', 'time'],
                'unique_together': {('tour', 'date', 'time')},
            },
        ),
        migrations.CreateModel(
            name='TourOptionPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('early_bird_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_child_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_pricing', to='tours.tour')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_pricing', to='tours.vehicletype')),
            ],
            options={
                'verbose_name': 'Tour Option Pricing',
                'verbose_name_plural': 'Tour Option Pricing',
                'unique_together': {('tour', 'vehicle_type')},
            },
        ),
        migrations.CreateModel(
            name='DepartureCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_capacity', models.PositiveIntegerField(help_text='Total seats for this vehicle type on this departure')),
                ('booked_count', models.PositiveIntegerField(default=0, help_text='Seats confirmed or held across all channels')),
                ('blocked_seats', models.PositiveIntegerField(default=0, help_text='Admin-blocked seats (not for sale)')),
                ('reattempt_reserved', models.PositiveIntegerField(default=0, help_text='Seats reserved for guaranteed re-attempt guests')),
                ('price_override_adult', models.DecimalField(blank=True, decimal_places=2, help_text='Override adult price for this specific departure. Leave blank to use tour option pricing.', max_digits=10, null=True)),
                ('price_override_child', models.DecimalField(blank=True, decimal_places=2, help_text='Override child price for this specific departure. Leave blank to use tour option pricing.', max_digits=10, null=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to='tours.departure')),
                ('vehicle_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_capacities', to='tours.vehicletype')),
            ],
            options={
                'verbose_name': 'Departure Capacity',
                'verbose_name_plural': 'Departure Capacities',
                'unique_together': {('departure', 'vehicle_type')},
            },
        ),
    ]
