# Generated by Django 6.1 on 2026-09-07 08:22

from django.db import migrations


def seed_vehicle_types(apps, schema_editor):
    VehicleType = apps.get_model('tours', 'VehicleType')
    vehicle_types = [
        {'name': 'Private Car', 'slug': 'private-car', 'default_capacity': 4, 'icon': '🚗', 'description': 'Ideal for couples and small families. Luxury private car with 4 seats.', 'sort_order': 1},
        {'name': 'Micro', 'slug': 'micro', 'default_capacity': 12, 'icon': '🚐', 'description': 'Perfect for big families and small groups. Comfortable microbus with 12 seats.', 'sort_order': 2},
        {'name': 'Group Bus', 'slug': 'group-bus', 'default_capacity': 54, 'icon': '🚌', 'description': 'Designed for large groups. Full-size tour bus with 54 seats.', 'sort_order': 3},
    ]
    for vt in vehicle_types:
        try:
            VehicleType.objects.get_or_create(slug=vt['slug'], defaults=vt)
        except Exception:
            vt_fallback = dict(vt)
            fallback_icons = {'private-car': 'car', 'micro': 'van', 'group-bus': 'bus'}
            vt_fallback['icon'] = fallback_icons.get(vt['slug'], 'car')
            VehicleType.objects.get_or_create(slug=vt_fallback['slug'], defaults=vt_fallback)


def reverse_seed(apps, schema_editor):
    VehicleType = apps.get_model('tours', 'VehicleType')
    VehicleType.objects.filter(slug__in=['private-car', 'micro', 'group-bus']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0011_vehicletype_tour_has_guaranteed_reattempt_departure_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_vehicle_types, reverse_seed),
    ]
