# Generated by Django 6.1 on 2026-09-07 08:35

import datetime
from decimal import Decimal
from django.db import migrations


def seed_tour_option_pricing_and_departures(apps, schema_editor):
    Tour = apps.get_model('tours', 'Tour')
    TourDate = apps.get_model('tours', 'TourDate')
    TourPricing = apps.get_model('tours', 'TourPricing')
    VehicleType = apps.get_model('tours', 'VehicleType')
    TourOptionPricing = apps.get_model('tours', 'TourOptionPricing')
    Departure = apps.get_model('tours', 'Departure')
    DepartureCapacity = apps.get_model('tours', 'DepartureCapacity')

    vehicle_types = {vt.slug: vt for vt in VehicleType.objects.all()}
    if not vehicle_types:
        return

    # 1. Seed TourOptionPricing for all tours across all 3 vehicle types
    for tour in Tour.objects.all():
        adult_pricing = TourPricing.objects.filter(tour=tour, label__iexact='Adult').first()
        child_pricing = TourPricing.objects.filter(tour=tour, label__iexact='Child').first()

        if adult_pricing:
            base_adult = adult_pricing.price
        else:
            first_p = TourPricing.objects.filter(tour=tour).first()
            base_adult = first_p.price if first_p else Decimal('100.00')

        if child_pricing:
            base_child = child_pricing.price
        else:
            base_child = (base_adult * Decimal('0.5')).quantize(Decimal('0.01'))

        # Pricing rules per vehicle tier:
        # Private Car: 30% premium (luxury private vehicle)
        # Micro: standard base price (family/small group)
        # Group Bus: 15% discount (large group value)
        tiers = [
            ('private-car', Decimal('1.30'), Decimal('1.30')),
            ('micro', Decimal('1.00'), Decimal('1.00')),
            ('group-bus', Decimal('0.85'), Decimal('0.85')),
        ]

        for slug, adult_mult, child_mult in tiers:
            vt = vehicle_types.get(slug)
            if not vt:
                continue
            adult_p = (base_adult * adult_mult).quantize(Decimal('0.01'))
            child_p = (base_child * child_mult).quantize(Decimal('0.01'))

            TourOptionPricing.objects.get_or_create(
                tour=tour,
                vehicle_type=vt,
                defaults={
                    'adult_price': adult_p,
                    'child_price': child_p,
                    'currency': 'EUR',
                    'is_active': True,
                }
            )

    # 2. Migrate existing TourDate records into Departure + DepartureCapacity
    for td in TourDate.objects.all():
        tour_title_lower = td.tour.title.lower()
        if 'aurora' in tour_title_lower or 'northern lights' in tour_title_lower:
            dep_time = datetime.time(20, 0)
        else:
            dep_time = datetime.time(10, 0)

        status_val = 'OPEN' if td.status == 'AVAILABLE' else ('SOLD_OUT' if td.status == 'SOLD_OUT' else 'CLOSED')

        dep, _ = Departure.objects.get_or_create(
            tour=td.tour,
            date=td.start_date,
            time=dep_time,
            defaults={
                'status': status_val,
                'notes': td.notes or '',
            }
        )

        for slug, vt in vehicle_types.items():
            if slug == 'micro':
                # Micro gets the original TourDate capacity and booked_count
                tot_cap = td.total_capacity if td.total_capacity else vt.default_capacity
                b_count = min(td.booked_count, tot_cap)
            else:
                tot_cap = vt.default_capacity
                b_count = 0

            DepartureCapacity.objects.get_or_create(
                departure=dep,
                vehicle_type=vt,
                defaults={
                    'total_capacity': tot_cap,
                    'booked_count': b_count,
                    'blocked_seats': 0,
                    'reattempt_reserved': 0,
                }
            )


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0012_seed_vehicle_types'),
    ]

    operations = [
        migrations.RunPython(seed_tour_option_pricing_and_departures, reverse_migration),
    ]
