# Generated by Django 6.1 on 2026-09-19 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_guarantee_system_overhaul'),
        ('tours', '0013_migrate_tour_dates_and_seed_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='guarantee_policy',
            field=models.ForeignKey(blank=True, help_text='Assign a configurable guarantee policy to this tour. Different packages can use different guarantee policies independently.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='bookings.guaranteepolicy'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='has_guaranteed_reattempt',
            field=models.BooleanField(default=False, help_text='DEPRECATED: Use guarantee_policy FK instead. Will be removed in a future migration.'),
        ),
    ]
