# Generated by Django 6.1 on 2026-09-22 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_guarantee_system_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancellationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Standard 48h Policy, Flexible Policy', max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text='Customer-facing description shown on tour page')),
                ('is_default', models.BooleanField(default=False, help_text='If True, this policy applies to tours without an explicit policy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cancellation Policy',
                'verbose_name_plural': 'Cancellation Policies',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('languages', models.JSONField(blank=True, default=list, help_text='List of languages, e.g. ["English", "Finnish", "Swedish"]')),
                ('certifications', models.TextField(blank=True, help_text='Certifications, licenses, qualifications')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Guide',
                'verbose_name_plural': 'Guides',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='departure',
            name='cutoff_hours_override',
            field=models.PositiveIntegerField(blank=True, help_text='Override tour-level cutoff hours for this specific departure. Leave blank to use tour default.', null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='cutoff_hours',
            field=models.PositiveIntegerField(default=24, help_text='Minimum hours before departure that bookings are accepted. 0 = no cutoff.'),
        ),
        migrations.AddField(
            model_name='tour',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If True, this tour/transfer is free — collect customer info only, skip payment'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='cancellation_terms',
            field=models.TextField(blank=True, default='', help_text='Legacy free-text cancellation terms (displayed if no CancellationPolicy assigned)'),
        ),
        migrations.CreateModel(
            name='BookingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text="e.g. 'What hotel are you staying at?', 'What is your shoe size?'", max_length=300)),
                ('field_type', models.CharField(choices=[('TEXT', 'Short Text'), ('TEXTAREA', 'Long Text'), ('SELECT', 'Dropdown Select'), ('NUMBER', 'Number'), ('YES_NO', 'Yes / No')], default='TEXT', max_length=10)),
                ('options', models.JSONField(blank=True, default=list, help_text='For SELECT type: list of options, e.g. ["Small", "Medium", "Large"] ')),
                ('is_required', models.BooleanField(default=False, help_text='If True, customer must answer before booking')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_questions', to='tours.tour')),
            ],
            options={
                'verbose_name': 'Booking Question',
                'verbose_name_plural': 'Booking Questions',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='tour',
            name='cancellation_policy',
            field=models.ForeignKey(blank=True, help_text='Assign a structured cancellation policy with tiered refund rules', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tours', to='tours.cancellationpolicy'),
        ),
        migrations.CreateModel(
            name='CancellationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_before_departure', models.PositiveIntegerField(help_text='Minimum hours before departure for this rule to apply. E.g., 48 = rule applies if cancelled 48+ hours before.')),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100.0, help_text='Refund percentage. 100 = full refund, 50 = half refund, 0 = no refund', max_digits=5)),
                ('description', models.CharField(blank=True, help_text="Customer-facing description, e.g. 'Free cancellation', '50% refund', 'No refund'", max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='tours.cancellationpolicy')),
            ],
            options={
                'verbose_name': 'Cancellation Rule',
                'verbose_name_plural': 'Cancellation Rules',
                'ordering': ['-hours_before_departure'],
            },
        ),
        migrations.CreateModel(
            name='DepartureGuideAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEAD_GUIDE', 'Lead Guide'), ('ASSISTANT', 'Assistant Guide'), ('DRIVER', 'Driver'), ('PHOTOGRAPHER', 'Photographer')], default='LEAD_GUIDE', max_length=20)),
                ('confirmed', models.BooleanField(default=False, help_text='Guide has confirmed availability')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_assignments', to='tours.departure')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tours.guide')),
            ],
            options={
                'verbose_name': 'Guide Assignment',
                'verbose_name_plural': 'Guide Assignments',
                'ordering': ['role', 'guide__full_name'],
                'unique_together': {('departure', 'guide')},
            },
        ),
    ]
