# Generated by Django 6.1 on 2026-09-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0015_cancellationpolicy_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingquestion',
            name='options',
            field=models.JSONField(blank=True, default=list, help_text='For SELECT type: list of options, e.g. ["Small", "Medium", "Large"]'),
        ),
    ]
