# Generated by Django 6.1 on 2026-08-31 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=250, unique=True)),
                ('new_path', models.CharField(max_length=250)),
                ('redirect_type', models.CharField(choices=[('PERMANENT_301', '301 Permanent'), ('TEMPORARY_302', '302 Temporary')], default='PERMANENT_301', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('seo_title', models.CharField(max_length=60)),
                ('meta_description', models.CharField(max_length=160)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=60, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
                ('robots_directive', models.CharField(default='index,follow', max_length=50)),
                ('structured_data', models.JSONField(blank=True, help_text='JSON-LD markup', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'SEO Metadata',
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
