# Generated by Django 6.1 on 2026-09-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactsubmission_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'General Inquiries'), ('TOURS', 'Tours & Experiences'), ('CHAUFFEUR', 'Chauffeur & Transfers'), ('PAYMENT', 'Booking & Payments'), ('WINTER', 'Winter Gear & Weather')], default='GENERAL', max_length=20)),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('author_location', models.CharField(help_text='e.g. London, United Kingdom', max_length=150)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('tour_name', models.CharField(blank=True, help_text='Tour they experienced', max_length=200)),
                ('rating', models.IntegerField(default=5)),
                ('quote', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'verbose_name': 'Site Setting', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(default='© 2026 Nord Velocity Oy. All rights reserved.', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='currency_symbol',
            field=models.CharField(default='€', max_length=5),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='emergency_phone',
            field=models.CharField(blank=True, default='+358 40 987 6543', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='facebook_url',
            field=models.URLField(blank=True, default='https://facebook.com/nordvelocity'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='google_maps_embed_url',
            field=models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1984.7!2d24.945!3d60.168!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zNjDCsDEwJzA0LjgiTiAyNMKwNTYnNDIuMCJF!5e0!3m2!1sen!2sfi!4v1600000000000!5m2!1sen!2sfi'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='Curated Arctic expeditions, glass igloo stays, and VIP chauffeur transfers across Finland and Scandinavia.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Discover the Untamed Beauty of the Nordics', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://instagram.com/nordvelocity'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='linkedin_url',
            field=models.URLField(blank=True, default='https://linkedin.com/company/nordvelocity'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='office_address',
            field=models.CharField(default='Pohjoisesplanadi 33, 00100 Helsinki, Finland', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='operating_hours',
            field=models.CharField(blank=True, default='Mon - Sun: 08:00 - 22:00 EET', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(default='Exclusive Nordic Tours & Luxury Chauffeur Services', max_length=250),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='tripadvisor_url',
            field=models.URLField(blank=True, default='https://tripadvisor.com'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(default='concierge@nordvelocity.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(default='+358 9 1234 567', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(default="Nord Velocity is Scandinavia's premier luxury travel designer, providing bespoke Arctic tours, private husky expeditions, and VIP chauffeur services."),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(default='Nord Velocity', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
