# Generated by Django 6.1 on 2026-09-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_faqitem_testimonial_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='bank_account_name',
            field=models.CharField(blank=True, default='Nord Velocity Oy', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_iban',
            field=models.CharField(blank=True, default='FI12 3456 7890 1234 56', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_name',
            field=models.CharField(blank=True, default='Nordea Bank Finland', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='bank_swift_bic',
            field=models.CharField(blank=True, default='NDEAFIFH', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='offline_payment_instructions',
            field=models.TextField(blank=True, default='You may pay upon arrival in cash (EUR) or by major credit card directly to your private chauffeur or concierge. For bank wire transfers, please transfer funds within 48 hours referencing your Booking Reference.'),
        ),
    ]
