# Generated by Django 6.1 on 2026-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesetting_bank_account_name_sitesetting_bank_iban_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Browser tab favicon (.ico, .png, .svg)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(blank=True, help_text='Main brand & navbar logo', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Social share preview banner (OpenGraph 1200x630)', null=True, upload_to='site/'),
        ),
    ]
