# Generated by Django 6.1 on 2026-09-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesetting_favicon_sitesetting_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Circle thumbnail image', null=True, upload_to='company_nav/')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Company Menu Item',
                'verbose_name_plural': 'Company Menu Items',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MegaMenuPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('DESTINATION', 'Destination Mega Menu Promo'), ('COMPANY', 'Company Mega Menu Promo'), ('TOUR', 'Tour Mega Menu Promo')], max_length=20, unique=True)),
                ('badge_text', models.CharField(blank=True, help_text="e.g. 'up to' or '2026'", max_length=50)),
                ('title', models.CharField(help_text="e.g. '30% off SALE' or '2026 Travel Report'", max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text="e.g. 'Winter Packages'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Promo description copy')),
                ('button_text', models.CharField(default='See Packages', max_length=50)),
                ('button_url', models.CharField(default='/tours/', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='megamenu/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mega Menu Promo Banner',
                'verbose_name_plural': 'Mega Menu Promo Banners',
            },
        ),
    ]
