# Generated by Django 6.1 on 2026-09-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_companymenuitem_megamenupromo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeOfferCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. NORDIC winter WONDERLAND', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Arctic Adventure awaits', max_length=150)),
                ('badge_text', models.CharField(blank=True, help_text='e.g. 25% off', max_length=50)),
                ('price_badge', models.CharField(blank=True, help_text='e.g. $199/only', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('url', models.CharField(default='/tours/', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Homepage Promotional Offer Card',
                'verbose_name_plural': 'Homepage Promotional Offer Cards',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartnerLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('url', models.CharField(blank=True, default='#', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Partner / Sponsor Logo',
                'verbose_name_plural': 'Partner / Sponsor Logos',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(help_text='e.g. CEO & Founder, Head of Arctic Operations', max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Leadership Team Member',
                'verbose_name_plural': 'Leadership Team Members',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Best Price Guarantee', max_length=150)),
                ('description', models.TextField()),
                ('icon_class', models.CharField(default='ph-bold ph-star', help_text='Phosphor icon class', max_length=100)),
                ('bg_color_class', models.CharField(default='bg-light-green', help_text='e.g. bg-light-green, bg-light-gray, bg-light-teal, bg-light-purple', max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Value Proposition / Feature',
                'verbose_name_plural': 'Value Propositions / Features',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='app_active_users',
            field=models.CharField(default='2M+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='app_rating',
            field=models.CharField(default='4.9', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='app_reviews_count',
            field=models.CharField(default='12,300+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='app_store_url',
            field=models.URLField(blank=True, default='https://apple.com/app-store'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_name',
            field=models.CharField(default='Nord Velocity Team', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='founder_title',
            field=models.CharField(default='Founder & Managing Director', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission_description',
            field=models.TextField(default='Discover the magic of the Arctic with the experts. We offer unparalleled experiences across the breathtaking landscapes of Finland.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission_statement',
            field=models.TextField(default='To provide authentic, unforgettable Nordic adventures while promoting sustainable tourism and respecting local traditions.'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission_title',
            field=models.CharField(default="We're Top Travel Agency in the Nordics.", max_length=200),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='play_store_url',
            field=models.URLField(blank=True, default='https://play.google.com'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_happy_travelers',
            field=models.CharField(default='15,000+', help_text='e.g. 15,000+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_rating_display',
            field=models.CharField(default='4.9', help_text='e.g. 4.9', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_satisfaction_rate',
            field=models.CharField(default='98%', help_text='e.g. 98%', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_tours_completed',
            field=models.CharField(default='26K+', help_text='e.g. 26K+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='stat_years_experience',
            field=models.CharField(default='15+', help_text='e.g. 15+', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vision_statement',
            field=models.TextField(default='To be the global benchmark for Arctic travel, ensuring every guest leaves with a deep appreciation for the North.'),
        ),
    ]
