# Generated by Django 6.1 on 2026-09-03 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_homeoffercard_partnerlogo_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavbarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Navigation link label e.g. Home, Destination, Company, Tour, Transport, Contact', max_length=100)),
                ('url', models.CharField(default='/', help_text='Target URL or path', max_length=255)),
                ('icon', models.ImageField(blank=True, help_text='Upload nav icon image (SVG/PNG) managed from admin panel', null=True, upload_to='navbar/icons/')),
                ('menu_type', models.CharField(choices=[('NONE', 'Direct Link (No Menu)'), ('DESTINATION', 'Destination Mega Menu'), ('COMPANY', 'Company Mega Menu'), ('TOUR', 'Tour Mega Menu')], default='NONE', help_text='Attach a mega menu if applicable', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Navbar Item',
                'verbose_name_plural': 'Navbar Items',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
