# Generated by Django 6.1 on 2026-09-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_navbaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='High-resolution hero fallback background image', null=True, upload_to='site/hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_badge',
            field=models.CharField(blank=True, default='Bespoke Arctic Expeditions & VIP Chauffeur', help_text='Small pill badge above hero title', max_length=150),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_video_file',
            field=models.FileField(blank=True, help_text='Optional: Upload local MP4 background video (bypasses YouTube player entirely)', null=True, upload_to='site/videos/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_video_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/watch?v=ScMzIvxBSi4', help_text='YouTube video URL or embed link (e.g. https://www.youtube.com/watch?v=ScMzIvxBSi4)', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(default='Curated Arctic expeditions, glass igloo stays, and VIP chauffeur transfers across Finland and Scandinavia.', help_text='Supporting description below hero title'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(default='Discover the Untamed Beauty of the Nordics', help_text='Main heading in homepage hero banner', max_length=250),
        ),
    ]
