# Generated by Django 6.1 on 2026-09-03 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesetting_hero_background_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='hero_badge',
        ),
    ]
