# Generated by Django 6.1 on 2026-09-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_sitesetting_hero_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='app_active_users',
            field=models.CharField(blank=True, default='2M+', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='app_rating',
            field=models.CharField(blank=True, default='4.9', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='app_reviews_count',
            field=models.CharField(blank=True, default='12,300+', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, default='concierge@nordvelocity.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_phone',
            field=models.CharField(blank=True, default='+358 9 1234 567', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='copyright_text',
            field=models.CharField(blank=True, default='© 2026 Nord Velocity Oy. All rights reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='currency_symbol',
            field=models.CharField(blank=True, default='€', max_length=5),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='default_currency',
            field=models.CharField(blank=True, default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='footer_text',
            field=models.TextField(blank=True, default="Nord Velocity is Scandinavia's premier luxury travel designer, providing bespoke Arctic tours, private husky expeditions, and VIP chauffeur services."),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='founder_name',
            field=models.CharField(blank=True, default='Nord Velocity Team', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='founder_title',
            field=models.CharField(blank=True, default='Founder & Managing Director', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Optional: High-resolution hero fallback background image', null=True, upload_to='site/hero/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_subtitle',
            field=models.TextField(blank=True, default='Curated Arctic expeditions, glass igloo stays, and VIP chauffeur transfers across Finland and Scandinavia.', help_text='Supporting description below hero title (optional)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_title',
            field=models.CharField(blank=True, default='Discover the Untamed Beauty of the Nordics', help_text='Main heading in homepage hero banner (optional)', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_video_url',
            field=models.CharField(blank=True, default='https://www.youtube.com/watch?v=ScMzIvxBSi4', help_text='YouTube video URL or embed link (optional)', max_length=500),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mission_description',
            field=models.TextField(blank=True, default='Discover the magic of the Arctic with the experts. We offer unparalleled experiences across the breathtaking landscapes of Finland.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mission_statement',
            field=models.TextField(blank=True, default='To provide authentic, unforgettable Nordic adventures while promoting sustainable tourism and respecting local traditions.'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='mission_title',
            field=models.CharField(blank=True, default="We're Top Travel Agency in the Nordics.", max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='office_address',
            field=models.CharField(blank=True, default='Pohjoisesplanadi 33, 00100 Helsinki, Finland', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Upload OpenGraph (OG) image for social media share previews. Default is blank if not uploaded.', null=True, upload_to='site/og/', verbose_name='OG Image (Social Share)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_name',
            field=models.CharField(blank=True, default='Nord Velocity', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='stat_happy_travelers',
            field=models.CharField(blank=True, default='15,000+', help_text='e.g. 15,000+', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='stat_rating_display',
            field=models.CharField(blank=True, default='4.9', help_text='e.g. 4.9', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='stat_satisfaction_rate',
            field=models.CharField(blank=True, default='98%', help_text='e.g. 98%', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='stat_tours_completed',
            field=models.CharField(blank=True, default='26K+', help_text='e.g. 26K+', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='stat_years_experience',
            field=models.CharField(blank=True, default='15+', help_text='e.g. 15+', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='tagline',
            field=models.CharField(blank=True, default='Exclusive Nordic Tours & Luxury Chauffeur Services', max_length=250),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='vision_statement',
            field=models.TextField(blank=True, default='To be the global benchmark for Arctic travel, ensuring every guest leaves with a deep appreciation for the North.'),
        ),
    ]
