# Generated by Django 6.1 on 2026-09-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitesetting_app_active_users_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homeoffercard',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': 'Discounts & Offers Card', 'verbose_name_plural': 'Discounts & Offers Cards (Homepage)'},
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='badge_text',
            field=models.CharField(blank=True, help_text='Pink pill badge text e.g. 25% off', max_length=50),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='image',
            field=models.ImageField(blank=True, help_text='Card background image upload', null=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Toggle card visibility on homepage'),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='price_badge',
            field=models.CharField(blank=True, help_text='Red circular badge at bottom right e.g. $199/only or SALE', max_length=50),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='sort_order',
            field=models.IntegerField(default=0, help_text='Display position (0, 1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='subtitle',
            field=models.CharField(blank=True, help_text='Subtitle e.g. Lapland Snowmobile & Husky Safari', max_length=150),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='title',
            field=models.CharField(blank=True, help_text='Headline e.g. NORDIC WINTER WONDERLAND', max_length=150),
        ),
        migrations.AlterField(
            model_name='homeoffercard',
            name='url',
            field=models.CharField(blank=True, default='/tours/', help_text='Link destination when card is clicked', max_length=255),
        ),
    ]
