# Generated by Django 6.1 on 2026-09-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_homeoffercard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='partners_title',
            field=models.CharField(blank=True, default='Our 100+ valuable partner in the world-wide', help_text='Headline above partner logos marquee on homepage', max_length=200),
        ),
    ]
