# Generated by Django 6.1 on 2026-09-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesetting_partners_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='explore_award_1_count',
            field=models.CharField(blank=True, default='15,000+', max_length=50, verbose_name='Award 1 Count (e.g. 15,000+ or 5,000,000)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_award_1_label',
            field=models.CharField(blank=True, default='Trusted Travelers', max_length=100, verbose_name='Award 1 Label'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_award_2_title',
            field=models.CharField(blank=True, default='BEST ARCTIC TOUR AWARD', max_length=100, verbose_name='Award 2 Title'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_award_2_year',
            field=models.CharField(blank=True, default='2026', max_length=20, verbose_name='Award 2 Year'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_badge',
            field=models.CharField(blank=True, default="WE'RE #01 TRAVEL AGENCY IN GLOBALLY", help_text='Blue small badge text above the main heading', max_length=200, verbose_name='Explore Subtitle / Badge'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_button_text',
            field=models.CharField(blank=True, default='Discover More', max_length=100, verbose_name='Button Label'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_button_url',
            field=models.CharField(blank=True, default='/about/', max_length=255, verbose_name='Button Link URL'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_description_1',
            field=models.TextField(blank=True, default="Travel is more than visiting places - it's about discovering cultures, creating memories, and experiencing the world in a way that stays with you forever. Our travel agency is dedicated to designing seamless and inspiring journeys for explorers who want more than just a typical vacation.", verbose_name='Short Description (Paragraph 1)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_description_2',
            field=models.TextField(blank=True, default='Our team of passionate travel experts works closely with each traveler to understand their interests, preferences, and expectations. This allows us to create journeys that feel personal, well-organized, and truly extraordinary.', verbose_name='Short Description (Paragraph 2)'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_image_left',
            field=models.ImageField(blank=True, help_text='Left tilted card in fanned display (optional, falls back to default if not uploaded)', null=True, upload_to='site/explore/', verbose_name='Left Tilted Card Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_image_main',
            field=models.ImageField(blank=True, help_text='Front center card in fanned display (optional, falls back to default if not uploaded)', null=True, upload_to='site/explore/', verbose_name='Main Center Card Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_image_right',
            field=models.ImageField(blank=True, help_text='Right tilted card in fanned display (optional, falls back to default if not uploaded)', null=True, upload_to='site/explore/', verbose_name='Right Tilted Card Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='explore_title',
            field=models.CharField(blank=True, default='Explore the World With Confidence.', max_length=250, verbose_name='Explore Main Heading'),
        ),
    ]
