# Generated by Django 6.1 on 2026-09-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_sitesetting_explore_award_1_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='explore_award_1_count',
            field=models.CharField(blank=True, default='5,000,000', max_length=50, verbose_name='Award 1 Count (e.g. 15,000+ or 5,000,000)'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='explore_award_1_label',
            field=models.CharField(blank=True, default='Trusted by 5M Users', max_length=100, verbose_name='Award 1 Label'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='explore_award_2_title',
            field=models.CharField(blank=True, default='BEST CITY<br>TOUR AWARD', max_length=100, verbose_name='Award 2 Title'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='explore_award_2_year',
            field=models.CharField(blank=True, default='2025', max_length=20, verbose_name='Award 2 Year'),
        ),
    ]
