# Generated by Django 6.1 on 2026-09-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sitesetting_explore_award_1_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_video_url',
            field=models.CharField(blank=True, default='', help_text='Direct video URL (.mp4) (optional)', max_length=500),
        ),
    ]
